version: '3.7'
services:
  website:
    container_name: "website"
    hostname: "website"
    image: 'nearvanilla_com'
    build:
      context: .
    restart: unless-stopped
    ports:
      - '8000:8000'
