version: '3.7'
services:
  website:
    container_name: "website"
    hostname: "website"
    image: 'nginx:1.19.2'
    restart: unless-stopped
    volumes:
      - './src:/var/www/html:ro'
      - './config:/etc/nginx/conf.d:ro'
    ports:
      - '8080:80'
